# Numpy 

- Numpy is used mainly for mathematical and numerical computations 
- Multidimentional arrays, matrix.. 

- For installation: 
    `pip install numpy`
    
- Use cases: 
   - Array Handling 
   - Matrix Handling 
   - Mathematical operations 
   - Linear Algebra 
   - Statical Analysis 
   - Data Preprocessing 

In [ ]:
1. Arrays: Creating Arrays, Indexing, Slicing 

In [5]:
#Creating array from List 

import numpy as np 

#1D array 

arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)

#2D array 

arr2 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr2)


#3D array 

arr3 = np.array([[[1,2],[4,5]],[[4,5],[6,7]]])

print(arr3)


[1 2 3 4 5 6 7]
[[1 2 3 4 5]
 [5 6 7 8 9]]
[[[1 2]
  [4 5]]

 [[4 5]
  [6 7]]]


In [14]:
# Accessing arrays from special function 

zeros = np.zeros((3,2))
print(zeros)


ones = np.ones((3,3))
print(ones)


identity = np.eye(4)
print(identity)

#random values 

random_values = np.random.rand(3,3)
print(random_values)


sequence = np.arange(0, 1, 0.2)
print("Floating-Point Sequence:", sequence)

#array with evenly distributed numbers 

linspace_array = np.linspace(1,10,5)
print(linspace_array)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.35198876 0.05249869 0.26536712]
 [0.28864087 0.14398263 0.87064988]
 [0.67710436 0.17918272 0.41135103]]
Floating-Point Sequence: [0.  0.2 0.4 0.6 0.8]
[ 1.    3.25  5.5   7.75 10.  ]


In [22]:
#Indexing and slicing 
# It is like that of lists in python 

arr = np.array([10,20,30,40,50,60,70])
print(arr[0])
print(arr[-1])
print(arr[:3])



arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1[0,0])
print(arr1[0,1])
print(arr1[1,:])
print(arr1[:,2])


10
70
[10 20 30]
1
2
[4 5 6]
[3 6]


In [25]:
#Mathematical operations using numpy 


a = np.array([2,3,4,5,6])
b = np.array([3,4,5,6,7])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)


#broadcasting 

print(a+7)

[ 5  7  9 11 13]
[-1 -1 -1 -1 -1]
[ 6 12 20 30 42]
[0.66666667 0.75       0.8        0.83333333 0.85714286]
[     8     81   1024  15625 279936]
[ 9 10 11 12 13]


# Statistical operations using Numpy 
- We can compute all descriptive statics using numpy 





In [32]:
arr = np.array([10,20,30,40,50,60])


print(np.mean(arr))
print(np.median(arr))
print(np.sum(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))


percentile_25 = np.percentile(arr,25)
percentile_50 = np.percentile(arr, 50)
percentile_75 = np.percentile(arr, 75)


print(percentile_25, percentile_50, percentile_75)

35.0
35.0
210
17.07825127659933
291.6666666666667
10
60
22.5 35.0 47.5


# Matrix operations 

- We can compute all matrix operations using python like: 
    - Matrix addition/subtraction/ Multiplication  
    - Matrix Transpose/Inverse





In [8]:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix Addition
print(A + B)

# Matrix Multiplication (Element-wise)
print(A * B)

# Matrix Multiplication (Dot Product)
print(np.dot(A, B))  # [[19 22] [43 50]]

# Transpose of a Matrix
print(A.T)  # [[1 3] [2 4]]

# Inverse of a Matrix
print(np.linalg.inv(A))  # [[-2.   1. ] [ 1.5 -0.5]]

# Determinant of a Matrix
print(np.linalg.det(A))  # -2.0



[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [10]:

# Coefficients (A)
A = np.array([[1, 2, 19], [4, 33, 6], [7, 8, 9]])

# Constants (B)
B = np.array([14, 32, 50])

# Solve
X = np.linalg.solve(A, B)
print(X)





[6.52727273 0.10909091 0.38181818]


In [1]:
import numpy as np
# 1. Creating Arrays
a = np.array([1, 2, 3]) # 1D array
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
c = np.zeros((2, 3)) # Array of zeros
d = np.ones((2, 3)) # Array of ones
e = np.eye(3) # Identity matrix
f = np.arange(0, 10, 2) # Array from 0 to 10 with step 2
g = np.linspace(0, 1, 5) # 5 values from 0 to 1
# 2. Reshaping Arrays
h = np.arange(9).reshape(3, 3)
# 3. Indexing & Slicing
i = b[1, 2] # Access element at row 1, col 2
j = b[:, 1] # All rows, column 1
k = b[0, :] # First row, all columns
# 4. Mathematical Operations
l = a + 2 # Add scalar
m = b * 2 # Multiply by scalar
n = np.sqrt(a) # Square root
o = np.exp(a) # Exponential
p = np.sin(a) # Sine function
# 5. Aggregations
sum_all = np.sum(b) # Sum of all elements
mean_val = np.mean(b) # Mean
max_val = np.max(b) # Max value
min_val = np.min(b) # Min value
# 6. Random Numbers
rand_array = np.random.rand(3, 3) # Random values between 0 and 1
rand_int = np.random.randint(0, 10, (3, 3)) # Random integers
# 7. Matrix Operations
dot_product = np.dot(a, a.T) # Dot product
matrix_mult = np.matmul(b, b.T) # Matrix multiplication
# Print to verify
print("Array a:", a)
print("Reshaped h:\n", h)
print("Sum:", sum_all, "Mean:", mean_val, "Max:", max_val)

Array a: [1 2 3]
Reshaped h:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum: 21 Mean: 3.5 Max: 6


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
# Matrix Addition
print(A + B)

# Matrix Multiplication (Element-wise)
print(A * B)
# Matrix Multiplication (Dot Product)
print(np.dot(A, B))
# Transpose of a Matrix
print(A.T)
# Inverse of a Matrix
print(np.linalg.inv(A))
# Determinant of a Matrix
print(np.linalg.det(A))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


### Solving a System of Linear Equations
#### Solve:
2x+3y = 8
5x+7y =19

In [4]:
coefficients = np.array([[2, 3], [5, 7]])
constants = np.array([8, 19])
solution = np.linalg.solve(coefficients, constants)
print(solution)

[1. 2.]


## Solve:
### x+2y+4z =14
### 4x+9y+10z =16
### 7x+3y+9z=55

In [5]:
# Coefficients (A)
A = np.array([[1, 2, 4], [4, 9, 10], [7, 3, 9]])
# Constants (B)
B = np.array([14, 16, 55])
# Solve
X = np.linalg.solve(A, B)
print(X)

[ 3.08235294 -5.90588235  5.68235294]


### Using Matrix Inverse to Solve Equations
### AX = B
### X = A(Inverse)B

    3x+24 = 5
    7x+4y = 10

In [6]:
A = np.array([[3, 2], [7, 4]])
B = np.array([5, 10])
# Compute inverse of A
A_inv = np.linalg.inv(A)
# Compute solution
X = np.dot(A_inv, B)
print(X)

[8.8817842e-16 2.5000000e+00]


### Least Squares Solution
#### If a system has more equations than unknowns, it may not have an exact solution.
    A^T A x = A^T b
### Equation:
    x+y = 2
    2x+3y = 5
    4x+5y = 8


In [7]:
A = np.array([[1, 1], [2, 3], [4, 5]])
B = np.array([2, 5, 8])
# Least Squares Solution
X = np.linalg.lstsq(A, B, rcond=None)[0]
print(X) # Approximate solution

[0.16666667 1.5       ]


### Eigenvalues and Eigenvectors
#### For a matrix A, the eigenvalues and eigenvectors satisfy:
    Av = λv
    Where,
    In [6]:
    In [8]:
    • A is coe􀀁cient of matrix
    • λ is eigon value
    • v is eigon vector
###### Eigenvectors for square matrices are defined as non-zero vector values which when multiplied by the square matrices give the scaler multiple of the vector, i.e. we defne an eigenvector for matrix A to be “v” if it specifies the condition, Av = λv

In [8]:
A = np.array([[4, -2], [1, 1]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


# Pandas

#### Pandas is an open-source Python library used for data manipulation, analysis, and cleaning. It provides powerful data structures such as Series (1D) and DataFrames (2D) to efficiently handle structured data.
- Built on NumPy, allowing for fast numerical computations.
- Commonly used in **data science, machine learning, and exploratory data analysis (EDA).**
- Works well with *CSV, Excel, SQL databases, and JSON files.**
- For Instillation
    > `pip install pandas`